services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mariadb/mariadb.cnf:/etc/mysql/mariadb.conf.d/mariadb.cnf
      - ./mariadb/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "3306:3306"

  jobmanager:
    image: seatunnel:2.3.10-flink-1.16.3
    container_name: seatunnel
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 3
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      # flink plugins
      - ./flink/plugins:/opt/flink/lib/plugins
      # flink jobs
      - ./flink/jobs/job.sql:/opt/flink/jobs/job.sql
      # seatunnel config
      - ./seatunnel/config:/config
      # seatunnel plugins
      - ./seatunnel/plugins:/opt/seatunnel/plugins
      # seatunnel lib
      - ./seatunnel/lib:/opt/seatunnel/lib
      # seatunnel connectors
      - ./seatunnel/connectors:/opt/seatunnel/connectors
    deploy:
          replicas: 1

  taskmanager:
    image: seatunnel:2.3.10-flink-1.16.3
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 6
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      # flink plugins
      - ./flink/plugins:/opt/flink/lib/plugins
      # seatunnel config
      - ./seatunnel/config:/config
      # seatunnel plugins
      - ./seatunnel/plugins:/opt/seatunnel/plugins
      # seatunnel lib
      - ./seatunnel/lib:/opt/seatunnel/lib
      # seatunnel connectors
      - ./seatunnel/connectors:/opt/seatunnel/connectors
    deploy:
          replicas: 2