services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mariadb/mariadb.cnf:/etc/mysql/mariadb.conf.d/mariadb.cnf
      - ./mariadb/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "3306:3306"

  jobmanager:
    image: seatunnel:2.3.10-flink-1.16.3
    container_name: seatunnel
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 3
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      # flink plugins
      - ./flink/plugins/flink-s3-fs-hadoop-1.20.1.jar:/opt/flink/lib/plugins/flink-s3-fs-hadoop-1.20.1.jar
      - ./flink/plugins/flink-shaded-hadoop-3-3.1.1.7.2.9.0-173-9.0.jar:/opt/flink/lib/plugins/flink-shaded-hadoop-3-3.1.1.7.2.9.0-173-9.0.jar
      # flink jobs
      - ./flink/jobs/job.sql:/opt/flink/jobs/job.sql
      # seatunnel config
      - ./seatunnel/config:/config
      # seatunnel plugins
      - ./seatunnel/plugins/mssql-jdbc-9.5.0.jre8-preview.jar:/opt/seatunnel/plugins/mssql-jdbc-9.5.0.jre8-preview.jar
      - ./seatunnel/plugins/seatunnel-hadoop3-3.1.4-uber.jar:/opt/seatunnel/plugins/seatunnel-hadoop3-3.1.4-uber.jar
      - ./seatunnel/plugins/seatunnel-hadoop-aws.jar:/opt/seatunnel/plugins/seatunnel-hadoop-aws.jar
      # seatunnel lib
      - ./seatunnel/lib/mssql-jdbc-9.5.0.jre8-preview.jar:/opt/seatunnel/lib/mssql-jdbc-9.5.0.jre8-preview.jar
      - ./seatunnel/lib/seatunnel-hadoop3-3.1.4-uber.jar:/opt/seatunnel/lib/seatunnel-hadoop3-3.1.4-uber.jar
      - ./seatunnel/lib/seatunnel-hadoop-aws.jar:/opt/seatunnel/lib/seatunnel-hadoop-aws.jar
      # seatunnel connectors
      - ./seatunnel/connectors/connector-cdc-sqlserver-2.3.10.jar:/opt/seatunnel/connectors/connector-cdc-sqlserver-2.3.10.jar
      - ./seatunnel/connectors/connector-paimon-2.3.10.jar:/opt/seatunnel/connectors/connector-paimon-2.3.10.jar
      - ./seatunnel/connectors/seatunnel-transforms-v2-2.3.10.jar:/opt/seatunnel/connectors/seatunnel-transforms-v2-2.3.10.jar
    deploy:
          replicas: 1

  taskmanager:
    image: seatunnel:2.3.10-flink-1.16.3
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 6
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      # flink plugins
      - ./flink/plugins/flink-s3-fs-hadoop-1.20.1.jar:/opt/flink/lib/plugins/flink-s3-fs-hadoop-1.20.1.jar
      - ./flink/plugins/flink-shaded-hadoop-3-3.1.1.7.2.9.0-173-9.0.jar:/opt/flink/lib/plugins/flink-shaded-hadoop-3-3.1.1.7.2.9.0-173-9.0.jar
      # seatunnel config
      - ./seatunnel/config:/config
      # seatunnel plugins
      - ./seatunnel/plugins/mssql-jdbc-9.5.0.jre8-preview.jar:/opt/seatunnel/plugins/mssql-jdbc-9.5.0.jre8-preview.jar
      - ./seatunnel/plugins/seatunnel-hadoop3-3.1.4-uber.jar:/opt/seatunnel/plugins/seatunnel-hadoop3-3.1.4-uber.jar
      - ./seatunnel/plugins/seatunnel-hadoop-aws.jar:/opt/seatunnel/plugins/seatunnel-hadoop-aws.jar
      # seatunnel lib
      - ./seatunnel/lib/mssql-jdbc-9.5.0.jre8-preview.jar:/opt/seatunnel/lib/mssql-jdbc-9.5.0.jre8-preview.jar
      - ./seatunnel/lib/seatunnel-hadoop3-3.1.4-uber.jar:/opt/seatunnel/lib/seatunnel-hadoop3-3.1.4-uber.jar
      - ./seatunnel/lib/seatunnel-hadoop-aws.jar:/opt/seatunnel/lib/seatunnel-hadoop-aws.jar
      # seatunnel connectors
      - ./seatunnel/connectors/connector-cdc-sqlserver-2.3.10.jar:/opt/seatunnel/connectors/connector-cdc-sqlserver-2.3.10.jar
      - ./seatunnel/connectors/connector-paimon-2.3.10.jar:/opt/seatunnel/connectors/connector-paimon-2.3.10.jar
      - ./seatunnel/connectors/seatunnel-transforms-v2-2.3.10.jar:/opt/seatunnel/connectors/seatunnel-transforms-v2-2.3.10.jar
    deploy:
          replicas: 2